baseURL = "https://cashapp.github.io/hermit/"
title = "Hermit Docs"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
#theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
theme = "geekdoc"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

#  menu items
[[menu.main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[menu.main]]
  name = "FAQ"
  weight = 3
  url = "docs/faq/"

[[menu.main]]
  name = "Packages"
  weight = 3
  url = "https://github.com/cashapp/hermit-packages"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "github"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  geekdocLogo = "images/logo.svg"
  geekdocSearch = true
  geekdocNextPrev = true
  geekdocRepo = "https://github.com/cashapp/hermit"
  geekdocEditPath = "edit/master/docs/content"

