on:
  schedule:
    - cron: "0 0 * * *"
name: Scheduled Sanity Test
jobs:
  test:
    name: Full Sanity Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: "master"
      - name: Test packages
        run: |
          cd it/sanity
          CHANGES=$(git log master --raw --since="25 hours ago" | wc -l)
          if [ $CHANGES != "0" ]; then
            ./run.sh -a
          else
            echo "No changes in 25 hours to Hermit. Skipping test"
          fi
