on:
  schedule:
    - cron: "0 0 * * *"
name: Scheduled Sanity Test
jobs:
  test:
    name: Full Sanity Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: "master"
      - name: Test packages
        run: |
          cd it/sanity
          CHANGES=$(git log master --raw --since="25 hours ago" | wc -l)
          if [ $CHANGES != "0" ]; then
            ./run.sh -a
          else
            echo "No changes in 25 hours to Hermit. Skipping test"
          fi
